// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP1t0ocE_7HUu9cBV2x8M_ny6dG7CflIk',
    appId: '1:209417665268:web:f742cbb05e77ef7833fca1',
    messagingSenderId: '209417665268',
    projectId: 'unit-f241d',
    authDomain: 'unit-f241d.firebaseapp.com',
    storageBucket: 'unit-f241d.firebasestorage.app',
    measurementId: 'G-4L3HR1XNJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcu3GeUfCM7x21_tirgdlLEWOFXHmHAmg',
    appId: '1:209417665268:android:abe4c2f46c1eef8033fca1',
    messagingSenderId: '209417665268',
    projectId: 'unit-f241d',
    storageBucket: 'unit-f241d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADckpVJJ8WKf-EY7qaWlF82SJB1OM-PB0',
    appId: '1:209417665268:ios:2a81b12e32f6e73a33fca1',
    messagingSenderId: '209417665268',
    projectId: 'unit-f241d',
    storageBucket: 'unit-f241d.firebasestorage.app',
    iosBundleId: 'com.example.unitConverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADckpVJJ8WKf-EY7qaWlF82SJB1OM-PB0',
    appId: '1:209417665268:ios:2a81b12e32f6e73a33fca1',
    messagingSenderId: '209417665268',
    projectId: 'unit-f241d',
    storageBucket: 'unit-f241d.firebasestorage.app',
    iosBundleId: 'com.example.unitConverter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP1t0ocE_7HUu9cBV2x8M_ny6dG7CflIk',
    appId: '1:209417665268:web:6f8d6a7bc86f835433fca1',
    messagingSenderId: '209417665268',
    projectId: 'unit-f241d',
    authDomain: 'unit-f241d.firebaseapp.com',
    storageBucket: 'unit-f241d.firebasestorage.app',
    measurementId: 'G-WH1RTR944B',
  );
}
